version: "3.4"

networks:
  network_prtg:
    driver: bridge

services:
  postgres_prtg:
    image: postgres:10.0-alpine
    container_name: postgres_prtg
    ports:
        - "5432:5432"
    restart: always
    volumes:
        - db_volume:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: "prtg"
        POSTGRES_PASSWORD: "prtg"
        POSTGRES_DB: "prtg"
    networks:
        - network_prtg

  webapi_prtg:
    image: webapi_prtg
    container_name: webapi_prtg
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    environment:
        ConnectionStrings__prtgHost: postgres_prtg
        VIRTUAL_HOST: prtg-api.it-one.com.ar
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: prtg-api.it-one.com.ar
        LETSENCRYPT_EMAIL: reporteobras@it-one.com.ar

    ports:
      - "80"
    restart: always
    networks:
      - network_prtg
      - nginx-proxy

  webapp_prtg:
    image: webapp_prtg
    container_name: webapp_prtg
    build:
      context: .
      dockerfile: src/WebApplication/Dockerfile
    environment:
        VIRTUAL_HOST: prtg.it-one.com.ar
        VIRTUAL_PORT: 80
        LETSENCRYPT_HOST: prtg.it-one.com.ar
        LETSENCRYPT_EMAIL: reporteobras@it-one.com.ar
    ports:
      - "80"
    restart: always
    networks:
      - nginx-proxy

volumes:
    db_volume:

networks:
  proxy:
    external:
      name: nginx-proxy
  network_prtg: