/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dfab4ebd-c444-47ba-a0e9-bb1570a170bc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KVSHzDQh2",
    "aws_user_pools_web_client_id": "6gku38a8b2cmpkasjf2iqthqfs",
    "oauth": {}
};


export default awsmobile;
