// <auto-generated />
using System;
using ApplicationCore.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApplicationCore.EntityFramework.Migrations
{
    [DbContext(typeof(PrtgDbContext))]
    [Migration("20200724232115_addDailyTonersValues")]
    partial class addDailyTonersValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApplicationCore.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("ApplicationCore.Models.Contract", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("BlackAndWhitePrice")
                        .HasColumnType("real");

                    b.Property<int>("BlackAndWhiteSheets")
                        .HasColumnType("integer");

                    b.Property<float>("ColorPrice")
                        .HasColumnType("real");

                    b.Property<int>("ColorSheets")
                        .HasColumnType("integer");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<float>("ExcedenteBlackAndWhitePrice")
                        .HasColumnType("real");

                    b.Property<float>("ExcedenteColorPrice")
                        .HasColumnType("real");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("PrinterObjId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PrinterObjId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("ApplicationCore.Models.Device", b =>
                {
                    b.Property<string>("ObjId")
                        .HasColumnType("text");

                    b.HasKey("ObjId");

                    b.ToTable("Device");
                });

            modelBuilder.Entity("ApplicationCore.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContractId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ApplicationCore.Models.Reports.DailyContadoresDataDevices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BlackAndWhiteCopies")
                        .HasColumnType("integer");

                    b.Property<int>("ColorCopies")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceObjId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceObjId");

                    b.ToTable("DailyContadores");
                });

            modelBuilder.Entity("ApplicationCore.Models.Reports.DailyTonersDataDevices", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BlackTonersUsed")
                        .HasColumnType("integer");

                    b.Property<int>("CyanTonersUsed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeviceObjId")
                        .HasColumnType("text");

                    b.Property<int>("MagentaTonersUsed")
                        .HasColumnType("integer");

                    b.Property<int>("YellowTonersUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceObjId");

                    b.ToTable("DailyToners");
                });

            modelBuilder.Entity("ApplicationCore.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<long?>("ContractId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("ContractId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ApplicationCore.Models.Contract", b =>
                {
                    b.HasOne("ApplicationCore.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("ApplicationCore.Models.Device", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterObjId");
                });

            modelBuilder.Entity("ApplicationCore.Models.Employee", b =>
                {
                    b.HasOne("ApplicationCore.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.HasOne("ApplicationCore.Models.Contract", null)
                        .WithMany("Employees")
                        .HasForeignKey("ContractId");
                });

            modelBuilder.Entity("ApplicationCore.Models.Reports.DailyContadoresDataDevices", b =>
                {
                    b.HasOne("ApplicationCore.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceObjId");
                });

            modelBuilder.Entity("ApplicationCore.Models.Reports.DailyTonersDataDevices", b =>
                {
                    b.HasOne("ApplicationCore.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceObjId");
                });

            modelBuilder.Entity("ApplicationCore.Models.User", b =>
                {
                    b.HasOne("ApplicationCore.Models.Contract", null)
                        .WithMany("UsersId")
                        .HasForeignKey("ContractId");
                });
#pragma warning restore 612, 618
        }
    }
}
