// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRTG_Api.Models;

namespace PRTG_Api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20200304213225_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PRTG_Api.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlackAndWhiteSheets")
                        .HasColumnType("int");

                    b.Property<int>("BlackToner")
                        .HasColumnType("int");

                    b.Property<int>("ColorSheets")
                        .HasColumnType("int");

                    b.Property<int>("CyanToner")
                        .HasColumnType("int");

                    b.Property<int>("MagentaToner")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("NameOfCompañy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Printer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YellowToner")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.ToTable("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
